// Generated by https://quicktype.io

import { TipoJugadorEnum } from "../../enums/TipoUsuarioEnum";

export interface ScoreResponse {
  scoreUsuario1: number;
  scoreUsuario2: number;
  usuarioGanador: TipoJugadorEnum;
}
